# Generated by Django 2.1.7 on 2019-03-14 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dutch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dutchauction',
            options={'verbose_name_plural': 'The Dutch Auction'},
        ),
        migrations.AlterField(
            model_name='dutchauction',
            name='lead_bid_price',
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=5),
        ),
        migrations.AlterField(
            model_name='dutchbid',
            name='bid_price',
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=5),
        ),
    ]
