# Generated by Django 2.1.7 on 2019-03-14 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20190313_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(default='', max_length=20),
        ),
    ]
