# Generated by Django 2.1.7 on 2019-03-12 04:48

import auctions.auction_timer
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_class', models.CharField(choices=[('X', 'X'), ('Y', 'Y'), ('PATENT', 'Patent'), ('LICENSE', 'License'), ('PLANT', 'Plant')], default='X', max_length=10)),
                ('underlying_asset', models.CharField(choices=[('X', 'X'), ('Y', 'Y')], default='X', max_length=10)),
                ('grade', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('region', models.CharField(choices=[('West', 'Western Canada'), ('Central', 'Central Canada'), ('East', 'Eastern Canada'), ('Home', 'Home Office')], default='H', max_length=10)),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)])),
                ('unit_price', models.DecimalField(decimal_places=2, default=25.0, max_digits=10)),
                ('buy_it_now_price', models.DecimalField(decimal_places=2, default=25.0, max_digits=10)),
                ('high_bid', models.DecimalField(decimal_places=2, default=25.0, max_digits=10)),
                ('high_bid_id', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('closing_date', models.DateTimeField(blank=True, default=auctions.auction_timer.period_end)),
                ('opening_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='OPEN', max_length=10)),
                ('views', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Auctions',
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=25.0, max_digits=10)),
                ('shipping', models.CharField(default='Ground', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping', models.CharField(default='ground', max_length=10)),
                ('auction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auctions.Auction')),
            ],
        ),
    ]
