# Generated by Django 2.1.7 on 2019-03-12 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auctions', '0002_auto_20190312_0048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'verbose_name_plural': 'Bids'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name_plural': 'Bids'},
        ),
        migrations.AddField(
            model_name='transaction',
            name='seller',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='t_seller', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='t_status',
            field=models.CharField(choices=[('Processing', 'Transaction in Progress'), ('Cleared', 'Transaction Cleared')], default='Processing', max_length=10),
        ),
        migrations.AlterField(
            model_name='auction',
            name='buy_it_now_price',
            field=models.DecimalField(decimal_places=1, default=25.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='auction',
            name='high_bid',
            field=models.DecimalField(decimal_places=1, default=25.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='auction',
            name='unit_price',
            field=models.DecimalField(decimal_places=1, default=25.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bid',
            name='price',
            field=models.DecimalField(decimal_places=1, default=25.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bid',
            name='shipping',
            field=models.CharField(choices=[('Ground', 'Ground Frieght'), ('Air', 'Air Frieght')], default='Ground', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.Auction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_buyer', to=settings.AUTH_USER_MODEL),
        ),
    ]
