# Generated by Django 2.1.7 on 2019-03-15 16:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20190312_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000000)]),
        ),
    ]
